// <auto-generated />
using System;
using API_Financeiro_Next.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Financeiro_Next.Migrations
{
    [DbContext(typeof(EntidadesContext))]
    [Migration("20240217223140_Receita&Despesas")]
    partial class ReceitaDespesas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_Financeiro_Next.Models.DespesaFixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ReceitaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TituloDespesaFixa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ValorDespesaFixa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("DespesasFixas");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.DespesaVariavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ReceitaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TituloDespesaVariavel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ValorDespesaVariavel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("DespesaVariavels");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.Impostos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TipoImposto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TituloImposto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ValorImposto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Impostos");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.Orçamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TituloOrçamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orçamentos");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TituloProduto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.DespesaFixa", b =>
                {
                    b.HasOne("API_Financeiro_Next.Models.Receita", "Receita")
                        .WithMany("DespesaFixa")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.DespesaVariavel", b =>
                {
                    b.HasOne("API_Financeiro_Next.Models.Receita", "Receita")
                        .WithMany("DespesaVariavel")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.Receita", b =>
                {
                    b.Navigation("DespesaFixa");

                    b.Navigation("DespesaVariavel");
                });
#pragma warning restore 612, 618
        }
    }
}
