// <auto-generated />
using System;
using API_Financeiro_Next.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Financeiro_Next.Migrations
{
    [DbContext(typeof(EntidadesContext))]
    partial class EntidadesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_Financeiro_Next.Models.Beneficiarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeBeneficiario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Beneficiarios");
                });

           

            modelBuilder.Entity("API_Financeiro_Next.Models.ContasPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiariosId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoDespesa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiariosId");

                    b.HasIndex("CategoriasId");

                    b.ToTable("Contas");
                });

           

            modelBuilder.Entity("API_Financeiro_Next.Models.ContasPagar", b =>
                {
                    b.HasOne("API_Financeiro_Next.Models.Beneficiarios", "Beneficiarios")
                        .WithMany("ContasAPagar")
                        .HasForeignKey("BeneficiariosId");

                    b.HasOne("API_Financeiro_Next.Models.Categorias", "Categorias")
                        .WithMany("ContasAPagar")
                        .HasForeignKey("CategoriasId");

                    b.Navigation("Beneficiarios");

                    b.Navigation("Categorias");
                });

           

            

            modelBuilder.Entity("API_Financeiro_Next.Models.Beneficiarios", b =>
                {
                    b.Navigation("ContasAPagar");
                });

            modelBuilder.Entity("API_Financeiro_Next.Models.Categorias", b =>
                {
                    b.Navigation("ContasAPagar");
                });

          
        }
    }
}
